### ISSUE TITLE
Support  R-bootcamp 10.-14. August in Oslo?

### ISSUE THREAD

**Issue by lexnederbragt** [uio-carpentry/organisational#50]
See email from Henrik Ræder January 24th 2020

**Comment by arockenberger** [comment]
In general, yes.
I was, however, under the impression that the support will come via the Digital Scholarship Centre and not directly via Carpentry@UiO. Or am I misinformed?

**Comment by lexnederbragt** [comment]
I don't know about the DSC, all I know is the email Henrik sent. But if support is already arranged, feel free to close this ticket (and answer the email to Henrik with that information, maybe?)

**Comment by arockenberger** [comment]
I can close the issue, but I really feel it is not my place to answer Henrik. I think Matthew replied to this email since it was cc'd to him and I briefly heard Matthew talking about plans running it with the library as host/support about it in a meeting, but that's it.
We need to establish a way to handle inquiries that arrive via mailing lists; at least it should be clear who "takes" a case and responds, so it doesn't sit in our inboxes…
