### ISSUE TITLE
Agenda for next board meeting (2021 Spring)

### ISSUE THREAD

**Issue by naoe-tatara** [uio-carpentry/organisational#92]
Please add items to discuss.

- [x] Introductions, and welcome Aino! (all, 5 minutes)
- [x] [Carpentries membership tier level](https://carpentries.org/membership/) (what we want and what could be reasonable): Naoe (10 minutes)
- [x] Use of announcement email list for other workshops than Carpentry-lesson based workshops: Naoe (10 minutes)
- [x] Use of [HackMD team space for Carpentry@UiO ](https://hackmd.io/team/uio-carpentry?nav=overview): Naoe (5 minutes)
- [x] Licence of Carpentry@UiO logo mark: Naoe (5 minutes)
- [x] Board member election: Lex (5 minutes) 
- [x] Discussion: Carpentry@UiO community engagement. Please read this post on The Carpentries blog before the meeting: [Pondering on the Question of Community Sustainability](https://carpentries.org/blog/2021/04/community-sustainability/): Lex (20 minutes)

**Comment by Teebusch** [comment]
@naoe-tatara How should we proceed with the meeting minutes? Until now we have always stored them here: https://github.com/uio-carpentry/organisational/tree/master/meetings

[It is possible to sync hackmd notes with github](https://hackmd.io/c/tutorials/%2Fs%2Flink-with-github). One needs to authorize hackmd to access the repo. I've done it before and it works quite well. Should I try to set this up for the meeting minutes, too?

**Comment by naoe-tatara** [comment]
Yes, I think synchronizing HackMD to this repo is a good solution. My understanding is that one can choose which repo to use for each HackMD note, right? You have manager privilege in the HackMD team space but it seems that you are "member" of this GH account (i.e. uio-carpentry). Does one need owner privilege to sync? If so, I will change your role to owner of both (at least for temporary purpose).

**Comment by Teebusch** [comment]
Yes, you can sync a note with any repo you want. YOu only have to authorize HackMD for that repo first.

I tried to sync the note with this repo. I got to a point where I can ask for authorization for the "HackMD Github app" to rea/write the repo. I think this request is now "pending" and must be approved by someone with owner rights for the repo. 

Can you check if you can see the request somewhere? (try https://hackmd.io/settings#integration or https://github.com/apps/hackmd-hub > "Configure")

Maybe it's not necessary for me to be owner once the HackMD app has access to the repo? Otherwise we can try the temporary owner thing you suggest, but I suspect it will only work as long as I'm owner.

**Comment by naoe-tatara** [comment]
I pushed the HackMD minute to the organizational/meetings (now it is in a separate branch "naoe-hackmd-integration-test"). Not sure if in future you or others can push from the HackMD, so can you @Teebusch try with a test HackMD note, please? I could not find how to change the owner of the HackMD Team space, but if you can find it, it should be also done.

**Comment by Teebusch** [comment]
It worked!

- I pushed to master now: https://github.com/uio-carpentry/organisational/blob/master/meetings/210430_board_meeting.md
- changed the note title (wrong year, sorry, may mistake!)
- added a "collaborate on HackMD batch" to the notes. editing only works for members of our HackMD team, I believe (which is what we want.
- [moved the `tags` to the yaml header](https://hackmd.io/s/how-to-tag-notes#Tagging-through-YAML-metadata) instead of [inline](https://hackmd.io/s/how-to-tag-notes#In-line-tags-with-auto-complete). Both work in HackMD, but I think using the header is more common generally and will also be easier to parse a yaml header with, e.g., Hugo. Tags for meeting minutes are also not so importat that they need to be in the document.
- updated the meeting minutes template (see `new note` > `note from template`)
- added info about HackMD to repo readme (see PR #93)

**Comment by naoe-tatara** [comment]
Great, thanks @Teebusch ! 
I don't quite get what the point 3 actually means. "the notes" here means the HackMD notes in the team space??

**Comment by Teebusch** [comment]
Ah, sorry, that wasn't very clear. I meant the meeting minutes from last weeks meeting. There is a badge at the start of the minutes now, that leads to the corresponding HackMD.

**Comment by naoe-tatara** [comment]
Got it! This is nice!
